safe: true
lsi: false
highlighter: rouge
future: true
markdown: kramdown
encoding: utf-8
kramdown:
  input: GFM
  hard_wrap: false
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
exclude: [
  "javascripts-dev",
  "node_modules"
]
livereload: true
